/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/debug-analytics`; params?: Router.UnknownInputParams; } | { pathname: `/exercise-detail`; params?: Router.UnknownInputParams; } | { pathname: `/exercise-library`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/program-builder`; params?: Router.UnknownInputParams; } | { pathname: `/workout-complete`; params?: Router.UnknownInputParams; } | { pathname: `/workout-in-progress`; params?: Router.UnknownInputParams; } | { pathname: `/workout-start`; params?: Router.UnknownInputParams; } | { pathname: `/workout-detail`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/analytics` | `/analytics`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/programs` | `/programs`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/debug-analytics`; params?: Router.UnknownOutputParams; } | { pathname: `/exercise-detail`; params?: Router.UnknownOutputParams; } | { pathname: `/exercise-library`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding`; params?: Router.UnknownOutputParams; } | { pathname: `/program-builder`; params?: Router.UnknownOutputParams; } | { pathname: `/workout-complete`; params?: Router.UnknownOutputParams; } | { pathname: `/workout-in-progress`; params?: Router.UnknownOutputParams; } | { pathname: `/workout-start`; params?: Router.UnknownOutputParams; } | { pathname: `/workout-detail`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/analytics` | `/analytics`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/programs` | `/programs`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/debug-analytics${`?${string}` | `#${string}` | ''}` | `/exercise-detail${`?${string}` | `#${string}` | ''}` | `/exercise-library${`?${string}` | `#${string}` | ''}` | `/onboarding${`?${string}` | `#${string}` | ''}` | `/program-builder${`?${string}` | `#${string}` | ''}` | `/workout-complete${`?${string}` | `#${string}` | ''}` | `/workout-in-progress${`?${string}` | `#${string}` | ''}` | `/workout-start${`?${string}` | `#${string}` | ''}` | `/workout-detail${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/analytics${`?${string}` | `#${string}` | ''}` | `/analytics${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/programs${`?${string}` | `#${string}` | ''}` | `/programs${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/debug-analytics`; params?: Router.UnknownInputParams; } | { pathname: `/exercise-detail`; params?: Router.UnknownInputParams; } | { pathname: `/exercise-library`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/program-builder`; params?: Router.UnknownInputParams; } | { pathname: `/workout-complete`; params?: Router.UnknownInputParams; } | { pathname: `/workout-in-progress`; params?: Router.UnknownInputParams; } | { pathname: `/workout-start`; params?: Router.UnknownInputParams; } | { pathname: `/workout-detail`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/analytics` | `/analytics`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/programs` | `/programs`; params?: Router.UnknownInputParams; };
    }
  }
}
